# Generated by Django 2.2.10 on 2023-04-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('stu_num', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='学号')),
                ('user', models.CharField(max_length=50, verbose_name='姓名')),
                ('password', models.CharField(default='123456', max_length=20, verbose_name='密码')),
                ('grade', models.PositiveIntegerField(verbose_name='年级')),
                ('dorm_build', models.CharField(choices=[('A', 'A栋'), ('B', 'B栋'), ('C', 'C栋'), ('D', 'D栋'), ('E', 'E栋'), ('4', '4栋'), ('5', '5栋'), ('6', '6栋')], default='', max_length=5, verbose_name='宿舍楼')),
                ('dorm_num', models.PositiveIntegerField(verbose_name='宿舍号')),
                ('institute', models.CharField(default='', max_length=100, verbose_name='学院')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=50, verbose_name='课程名称')),
                ('addr', models.CharField(default='', max_length=20, verbose_name='上课地点')),
                ('c_week', models.SmallIntegerField(verbose_name='上课时间(周次)')),
                ('c_period', models.CharField(default='', max_length=10, verbose_name='课节')),
                ('tech_name', models.CharField(default='', max_length=50, verbose_name='教师姓名')),
                ('stu_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='课表_学号', to='main.UserInfo')),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=2019, max_length=10, verbose_name='学年')),
                ('term', models.SmallIntegerField(choices=[(0, '全部'), (1, '第一学期'), (2, '第二学期'), (3, '第三学期')], default=1, verbose_name='学期')),
                ('cname', models.CharField(default='', max_length=100, verbose_name='课程名称')),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='成绩')),
                ('credit', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='学分')),
                ('gpa', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='绩点')),
                ('stu_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='学号', to='main.UserInfo')),
            ],
            options={
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=100, verbose_name='图书名称')),
                ('read_type', models.CharField(choices=[('已读', '已读'), ('在读', '在读')], default='', max_length=10, verbose_name='阅读情况')),
                ('borrow_date', models.DateField(verbose_name='借阅时间')),
                ('return_date', models.DateField(blank=True, verbose_name='归还时间')),
                ('stu_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='图书_学号', to='main.UserInfo')),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
    ]
