# Generated by Django 2.2.10 on 2023-04-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bname',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='brdate',
            new_name='borrow_date',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='rtype',
            new_name='read_type',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='redate',
            new_name='return_date',
        ),
    ]
