# Generated by Django 2.2.10 on 2023-04-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='year',
            field=models.IntegerField(default=2019, verbose_name='学年'),
        ),
    ]
