# Generated by Django 2.2.10 on 2023-04-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230417_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=50, verbose_name='课程名称')),
                ('addr', models.CharField(default='', max_length=20, verbose_name='上课地点')),
                ('c_week', models.SmallIntegerField(verbose_name='上课时间(周次)')),
                ('c_period', models.CharField(default='', max_length=10, verbose_name='课节')),
                ('tech_name', models.CharField(default='', max_length=50, verbose_name='教师姓名')),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
    ]
