# Generated by Django 4.0.5 on 2023-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230420_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='term',
            field=models.SmallIntegerField(choices=[(1, '第一学期'), (2, '第二学期')], default=1, verbose_name='学期'),
        ),
    ]
