# Generated by Django 2.2.10 on 2023-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='姓名')),
                ('grade', models.PositiveIntegerField(verbose_name='年级')),
                ('dorm_build', models.CharField(choices=[('A', 'A栋'), ('B', 'B栋'), ('C', 'C栋'), ('D', 'D栋'), ('E', 'E栋'), ('4', '4栋'), ('5', '5栋'), ('6', '6栋')], default='', max_length=5, verbose_name='宿舍楼')),
                ('dorm_num', models.PositiveIntegerField(verbose_name='宿舍号')),
                ('institute', models.CharField(default='', max_length=100, verbose_name='学院')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
    ]
