# Generated by Django 4.0.5 on 2023-04-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_score_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=50, verbose_name='教学楼编号')),
                ('room_num', models.PositiveIntegerField(verbose_name='教室编号')),
            ],
            options={
                'verbose_name': '教室',
            },
        ),
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '图书借阅信息'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': '成绩'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': '课程表'},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='c_period',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='c_week',
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_class',
            field=models.SmallIntegerField(default=14, verbose_name='结束节数'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_week',
            field=models.SmallIntegerField(default=18, verbose_name='课程结束周'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_class',
            field=models.SmallIntegerField(default=1, verbose_name='开始节数'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_week',
            field=models.SmallIntegerField(default=1, verbose_name='课程开始周'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='stu_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='读者编号', to='main.userinfo'),
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='考试课程')),
                ('begin_time', models.DateTimeField(verbose_name='考试开始时间')),
                ('end_time', models.DateTimeField(verbose_name='考试结束时间')),
                ('exam_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='考试地点', to='main.classroom')),
            ],
            options={
                'verbose_name': '考试',
                'db_table': 'ExamInfo',
            },
        ),
        migrations.AlterField(
            model_name='timetable',
            name='addr',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='上课地点', to='main.classroom'),
        ),
    ]
