# Generated by Django 4.0.5 on 2023-04-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_classroom_alter_bookinfo_options_alter_score_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classroom',
            table='classroom',
        ),
    ]
